# 🚀 Build and deploy Laravel (PHP 8.3) app to Azure Web App
name: Build and deploy PHP app to Azure Web App - aslaw-back-end

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, intl, pdo, pdo_mysql, openssl

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate Laravel app key
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D489C82A67404A39B371321D84D01288 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ADDFBF33F1E34CB68E69169C5D263C43 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F170708E314A429388A93A916D91B5F2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aslaw-back-end'
          slot-name: 'Production'
          package: .
